### ISSUE TITLE
Test name is not visible in UI and in status

### ISSUE THREAD

**Issue by testwareit** [alcounit/selenosis#18]
Hello!
I'm trying to add test name through capabilites, but I'm not able to do that. I was trying to do it in multiple ways, but no luck:
`        capabilities = {
            "browserName": "chrome",
            "name": "asfg",
            "testName": "att",
            "selenoid:options": {
                "enableVNC": False,
                "name": "test_name",
                "testName": "qwe"
            },
            "selenosis:options": {
                "enableVNC": False,
                "name": "test_name2",
                "testName": "qwe3"
            }
        }`

Test name is empty in UI but also in selenosis /status page:
`"labels":{"ENABLE_VNC":"true","SCREEN_RESOLUTION":"1920x1080x24","browserName":"chrome","browserVersion":"88.0","session":"selenoid-vnc-chrome-88-0-cce71b85-3593-4210-9c57-8bec060db64d","testName":"","type":"browser"`

Language: Python

**Comment by alcounit** [comment]
Hi @testwareit, thanks for reporting.
I updated selenosis version to v0.0.9-develop with fix https://github.com/alcounit/selenosis/commit/95fb99677b75ac91bf6393bc6d95a44074ca233c, can you please try from your side.
Updated manifest: https://github.com/alcounit/selenosis-deploy/blob/main/03-selenosis.yaml

**Comment by testwareit** [comment]
Works perfectly! 
Thanks for quick response :)

**Comment by alcounit** [comment]
Glad to hear it, thanks.
Will update README later.
