### ISSUE TITLE
a container name must be specified Session creation ERROR: for pod <VNC_CHROME>, choose one of: [browser seleniferous]

### ISSUE THREAD

**Issue by tarasmytlovych** [alcounit/selenosis#47]
Hi

This project looks ideal for our needs.
However, we experiencing error during Remote run session creation
The session is not created, pod is in status pending and in the logs of the pod the following error:
```error: a container name must be specified Session creation ERROR: for pod <VNC_CHROME>, choose one of: [browser seleniferous]```

How can it be fixed? Maybe, we have done something wrong?
For installation was used the following steps
https://github.com/alcounit/selenosis-deploy

To run tests we use java 
```
 DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("browserName", "chrome");
        capabilities.setCapability("browserVersion", "90.0");
        capabilities.setCapability("selenoid:options", Map.<String, Object>of(
                "enableVNC", true,
                "enableVideo", true,
                "name", "browser",
                "screenResolution", "2560x1600"
        ));

return new RemoteWebDriver(new URL(ConfigManager.getSeleniumUrl()), capabilities)
```
URL is like http://selenosis_LoadBalancer_EXTERNAL-IP:4444/wd/hub

Starting session from selenoid-ui produces the same error.

Tested with releases v1.0.4 and 1.0.5

Env
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"e1d093448d0ed9b9b1a48f49833ff1ee64c05ba5", GitTreeState:"clean", BuildDate:"2021-06-03T00:20:57Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by alcounit** [comment]
Hi @tarasmytlovych, thanks for the feedback.

selenosis doesn't support selenoid:options see https://github.com/alcounit/selenosis#run-yout-tests

Can you please share logs from selenosis and selenoid-ui and selenosis config?

**Comment by tarasmytlovych** [comment]
I've also tried as mentioned in the repo
```DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setBrowserName("chrome");
capabilities.setVersion("85.0");
```

But the result was the same.
From selenoid-ui session is also not starting. Pod logs have the same error

selenosis logs
```
time="2021-08-09T11:49:17Z" level=info msg="selenosis worker: selenosis-7f94c96c9f-csqpt added, current namespace quota limit: 13"
time="2021-08-09T11:49:17Z" level=info msg="selenosis worker: selenoid-ui-847c76bf88-dgk7s added, current namespace quota limit: 13"
time="2021-08-09T11:49:17Z" level=info msg="selenosis worker: selenosis-7f94c96c9f-9f2q6 added, current namespace quota limit: 13"
time="2021-08-09T11:49:51Z" level=info msg=session request="POST /wd/hub/session" request_id=cc66f179-62d5-401b-bcb7-0380ceb1aae5 time_elapsed=0.00s
time="2021-08-09T11:49:51Z" level=info msg="starting browser from image: selenoid/vnc:chrome_92.0" request="POST /wd/hub/session" request_id=cc66f179-62d5-401b-bcb7-0380ceb1aae5 time_elapsed=0.11s
```
kubectl pods shows vnc-chrome-92-0-cc82b5e0-a8d3-41f4-80c3-c7379f82fa6e   0/2     Pending   0          7m15s


selenoid-ui logs

```
    error: a container name must be specified for pod selenoid-ui-847c76bf88-dgk7s, choose one of: [selenoid-ui selenoid-ui-adapter]
```

https://github.com/alcounit/selenosis-deploy/blob/main/browsers.yaml

**Comment by alcounit** [comment]
ok, I need from you:

output of kubectl describe for browser pod (it is Pending state, need to understand why)

full selenosis log with session creation attempt 

bdw what **--browser-wait-timeout** have you set for selenosis?

**Comment by tarasmytlovych** [comment]
kubectl describe pod vnc-chrome-92-0-cc82b5e0-a8d3-41f4-80c3-c7379f82fa6e -n selenosis
'''Name:         vnc-chrome-92-0-cc82b5e0-a8d3-41f4-80c3-c7379f82fa6e
Namespace:    selenosis
Priority:     0
Node:         <none>
Labels:       selenosis.app.type=browser
              session=vnc-chrome-92-0-cc82b5e0-a8d3-41f4-80c3-c7379f82fa6e
              type=browser
Annotations:  capabilities: {"ENABLE_VNC":"true","browserName":"chrome","browserVersion":"92.0","testName":"Manual session"}
Status:       Pending
IP:
IPs:          <none>
Containers:
  browser:
    Image:       selenoid/vnc:chrome_92.0
    Ports:       5900/TCP, 4444/TCP
    Host Ports:  0/TCP, 0/TCP
    Environment:
      ENABLE_VNC:  true
    Mounts:
      /dev/shm from dshm (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-cc85t (ro)
  seleniferous:
    Image:      alcounit/seleniferous:v1.0.2
    Port:       4445/TCP
    Host Port:  0/TCP
    Command:
      /seleniferous
      --listhen-port
      4445
      --proxy-default-path
      /session
      --idle-timeout
      5m0s
      --namespace
      selenosis
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-cc85t (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  dshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  default-token-cc85t:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-cc85t
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  4m5s (x39 over 44m)  default-scheduler  0/1 nodes are available: 1 Too many pods.'''

kubectl logs selenosis-7f94c96c9f-9f2q6 -n selenosis

'''
time="2021-08-09T11:49:17Z" level=info msg="starting selenosis v1.0.5"
time="2021-08-09T11:49:17Z" level=info msg="browsers config file loaded"
time="2021-08-09T11:49:17Z" level=info msg="config watcher started"
time="2021-08-09T11:49:17Z" level=info msg="kubernetes client created"
time="2021-08-09T11:49:17Z" level=info msg="current cluster state: sessions - 0, workers - 3, session limit - 10"
time="2021-08-09T11:49:17Z" level=info msg="selenosis worker: selenosis-7f94c96c9f-csqpt added, current namespace quota limit: 13"
time="2021-08-09T11:49:17Z" level=info msg="selenosis worker: selenoid-ui-847c76bf88-dgk7s added, current namespace quota limit: 13"
time="2021-08-09T11:49:17Z" level=info msg="selenosis worker: selenosis-7f94c96c9f-9f2q6 added, current namespace quota limit: 13"
time="2021-08-09T11:49:51Z" level=info msg=session request="POST /wd/hub/session" request_id=cc66f179-62d5-401b-bcb7-0380ceb1aae5 time_elapsed=0.00s
time="2021-08-09T11:49:51Z" level=info msg="starting browser from image: selenoid/vnc:chrome_92.0" request="POST /wd/hub/session" request_id=cc66f179-62d5-401b-bcb7-0380ceb1aae5 time_elapsed=0.11s
'''

kubectl logs selenosis-7f94c96c9f-csqpt -n selenosis
'''time="2021-08-09T11:49:17Z" level=info msg="starting selenosis v1.0.5"
time="2021-08-09T11:49:17Z" level=info msg="browsers config file loaded"
time="2021-08-09T11:49:17Z" level=info msg="config watcher started"
time="2021-08-09T11:49:17Z" level=info msg="kubernetes client created"
time="2021-08-09T11:49:17Z" level=info msg="current cluster state: sessions - 0, workers - 3, session limit - 10"
time="2021-08-09T11:49:17Z" level=info msg="selenosis worker: selenosis-7f94c96c9f-csqpt added, current namespace quota limit: 13"
time="2021-08-09T11:49:17Z" level=info msg="selenosis worker: selenoid-ui-847c76bf88-dgk7s added, current namespace quota limit: 13"
time="2021-08-09T11:49:17Z" level=info msg="selenosis worker: selenosis-7f94c96c9f-9f2q6 added, current namespace quota limit: 13"'''

kubectl logs selenoid-ui-847c76bf88-dgk7s -c selenoid-ui -n selenosis
'''
[15:38] Oleg Kruts
    2021/08/09 11:46:57 [INIT] [Listening on :8080]
2021/08/09 11:49:42 Client added. 1 registered clients
2021/08/09 11:50:19 [ERROR] [Failed to proxy to http://selenosis:4444/wd/hub/session: context canceled]
'''


**--browser-wait-timeout** - din't change it. The default one

Also, our k8s is lived on Azure

**Comment by alcounit** [comment]
I see is that kubernetes can't schedule pod with browser, can you please any limits in namespace/node/cluster?
```log
Warning  FailedScheduling  4m5s (x39 over 44m)  default-scheduler  0/1 nodes are available: 1 Too many pods.
```

**Comment by tarasmytlovych** [comment]
what limits do you mean?
like limits on resources per pod (cpu, memory, etc) or some other?

**Comment by alcounit** [comment]
can you please check how many pods are scheduled on your node?
kubectl get nodes 
kubectl describe node <node_name>

**Comment by tarasmytlovych** [comment]
There are 30 and looks like the limit is reached.
Will try to increase the limit or delete some pods and retry with selenosis.

Thanks for now. 
Will post here the result when do it.

**Comment by alcounit** [comment]
If your problem will be solved, please close the ticket.

**Comment by tarasmytlovych** [comment]
The issue was fixed by extending the limits.
Thanks for your help!
