### ISSUE TITLE
Timeouts when running tests

### ISSUE THREAD

**Issue by mmamul2** [alcounit/selenosis#50]
Hi, 
I'm trying to get Selenosis up and running in a AKS cluster, but I'm running into "failed to start browser: container service" from the selenosis pod and "Waiting X server..." / session timeouts from the browser pod errors when attempting to run tests. 

Before diving too deep into debugging, I'm curious if Microsoft moving to Containerd and removing access to the Docker engine could be involved with the problem? I doubt it is related, but with the headaches that change has caused me, better to get an expert opinion.

Thanks

**Comment by alcounit** [comment]
Hi @mmamul2,

> Before diving too deep into debugging, I'm curious if Microsoft moving to Containerd and removing access to the Docker engine could be involved with the problem? I doubt it is related, but with the headaches that change has caused me, better to get an expert opinion.

I can't say anything about this, assume that if your cluster runs any other applications without a problem then probably that's not an issue.

>I'm trying to get Selenosis up and running in a AKS cluster, but I'm running into "failed to start browser: container service" from the selenosis pod and "Waiting X server..." / session timeouts from the browser pod errors when attempting to run tests.

What browser you are trying to test?
Share your browsers config and logs from selenosis and sidecar container

**Comment by mmamul2** [comment]
Attempting to use Firefox. The image is just the selenoid image saved to a private ACR. I think it may just be a communication issue and the deployment to VMs not being handled correctly. I'll try and track down the issue over the weekend and close the issue if I find it.

Browser config:
{        
    "firefox": {
        "defaultVersion": "77.0",
        "path": "/wd/hub",
        "kernelCaps": ["SYS_ADMIN"],
        "versions": {
            "77.0": {
                "image": "private/firefox:77.0"
            },
            "78.0": {
                "image": "selenoid/vnc:firefox_78.0"
            },
            "79.0": {
                "image": "selenoid/vnc:firefox_79.0"
            },
            "80.0": {
                "image": "selenoid/vnc:firefox_80.0"
            },
            "81.0": {
                "image": "selenoid/vnc:firefox_81.0"
            },
            "82.0": {
                "image": "selenoid/vnc:firefox_82.0"
            },
            "83.0": {
                "image": "selenoid/vnc:firefox_83.0"
            },
            "84.0": {
                "image": "selenoid/vnc:firefox_84.0"
            },
            "85.0": {
                "image": "selenoid/vnc:firefox_85.0"
            },
            "86.0": {
                "image": "selenoid/vnc:firefox_86.0"
            },
            "87.0": {
                "image": "selenoid/vnc:firefox_87.0"
            },
            "88.0": {
                "image": "selenoid/vnc:firefox_88.0"
            },
            "89.0": {
                "image": "selenoid/vnc:firefox_89.0"
            },
            "90.0": {
                "image": "selenoid/vnc:firefox_90.0"
            }
        }
    }
}
[BrowserLogs.txt](https://github.com/alcounit/selenosis/files/7694269/BrowserLogs.txt)
[SeleniferousLogs.txt](https://github.com/alcounit/selenosis/files/7694270/SeleniferousLogs.txt)
[SelenosisLogs.txt](https://github.com/alcounit/selenosis/files/7694271/SelenosisLogs.txt)

**Comment by mmamul2** [comment]
My apologies for the slow reply. I'm fairly certain it was related to communication within our Kubernetes cluster, but I never found the problem as I'm pretty new to Kubernetes. I've moved towards a different selenium solution since time was an issue and I needed to spin something up quickly. I'll close the issue.
